-- sniffer
-- -------

ALTER TABLE cdr
MODIFY COLUMN a_saddr VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN b_saddr VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN sipcalledip VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN sipcallerip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE cdr_proxy
MODIFY COLUMN dst VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE cdr_rtp
MODIFY COLUMN daddr VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN saddr VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE cdr_sdp
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE cdr_dtmf
MODIFY COLUMN daddr VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN saddr VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE message
MODIFY COLUMN sipcalledip VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN sipcallerip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE message_proxy
MODIFY COLUMN dst VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE register_state
MODIFY COLUMN sipcalledip VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN sipcallerip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE register_failed
MODIFY COLUMN sipcalledip VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN sipcallerip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE sip_msg
MODIFY COLUMN ip_dst VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN ip_src VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE ss7
MODIFY COLUMN dst_ip VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN src_ip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE rtp_stat
MODIFY COLUMN saddr VARBINARY(16) NOT NULL;

ALTER TABLE ssl_sessions
MODIFY COLUMN clientip VARBINARY(16) NOT NULL,
MODIFY COLUMN serverip VARBINARY(16) NOT NULL;

ALTER TABLE ssl_sessions_mem
MODIFY COLUMN clientip VARBINARY(16) NOT NULL,
MODIFY COLUMN serverip VARBINARY(16) NOT NULL;

ALTER TABLE cache_number_location
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN number_ip VARBINARY(16) NOT NULL,
MODIFY COLUMN old_ip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE cache_number_domain_location
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN number_ip VARBINARY(16) NOT NULL,
MODIFY COLUMN old_ip VARBINARY(16) NULL DEFAULT NULL;


-- livepacket (pro všechny tabulky livepacket%)
-- --------------------------------------------

ALTER TABLE livepacket
MODIFY COLUMN sipcalledip VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN sipcallerip VARBINARY(16) NULL DEFAULT NULL;


-- gui
-- ---

ALTER TABLE filter_ip
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE hostname
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE hostname_cache
MODIFY COLUMN ip VARBINARY(16) NOT NULL;

ALTER TABLE billing_customer_assignment_addresses
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE billing_operator_assignment_addresses
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE billing_exclude_addresses
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE billing_agregation_exclude_addresses
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL;

ALTER TABLE geoip_customer
MODIFY COLUMN ip VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN ip_from VARBINARY(16) NULL DEFAULT NULL,
MODIFY COLUMN ip_to VARBINARY(16) NULL DEFAULT NULL;


-- billing agregace (pokud existují tabulky)
-- -----------------------------------------

ALTER TABLE billing_agregation_hour_addresses
MODIFY COLUMN ip VARBINARY(16) NOT NULL;

ALTER TABLE billing_agregation_day_addresses
MODIFY COLUMN ip VARBINARY(16) NOT NULL;

ALTER TABLE billing_agregation_week_addresses
MODIFY COLUMN ip VARBINARY(16) NOT NULL;

ALTER TABLE billing_agregation_month_addresses
MODIFY COLUMN ip VARBINARY(16) NOT NULL;
